### DISCUSSION TITLE
Changing pseudo class styling

### DISCUSSION THREAD

**Discussion by JoeldelPilar** [gilbarbara/react-joyride#1029] [Q&A] [answered]
Hi! 👋🏼 
I'm using Joyride for the first time and I'm a junior frontend dev. I wonder if there is any way to change the styling of :focus on the tooltip? The default color of the outline when tab-ing to the buttons is not matching our color profile and if it is possible I would like to change the styling. 😃

**Comment by gilbarbara** [comment, marked as answer]
Hey @JoeldelPilar 

I think it's using the browser's default outline style.
You could target the CSS classes to change the globally.

```css
.react-joyride__beacon:focus,
.react-joyride__tooltip button:focus {
	outline: 1px solid #ff0044;
	border-radius: 2px;
}
```

Or use a custom tooltip where you can customize everything.

Good luck.
