### DISCUSSION TITLE
animation for sportlight

### DISCUSSION THREAD

**Discussion by vhphuc0240** [gilbarbara/react-joyride#1066] [Ideas]
I want to add animation to sportlight for attractive to users. Some animation like that: https://codesandbox.io/p/sandbox/confident-feynman-qxyzq5 or any animation with lottie

**Comment by gilbarbara** [comment]
Hey @vhphuc0240 

You can add the keyframes and the selector in your global CSS.

```css
@keyframes scaleUpDown {
    0% {
        transform: scale(1); /* Start at normal size */
    }
    50% {
        transform: scale(1.2); /* Scale up */
    }
    100% {
        transform: scale(1); /* Scale back down */
    }
}

.react-joyride__spotlight {
	animation: scaleUpDown 2s infinite;
}
```
