### ISSUE TITLE
css-module causes issue with @keyframes

### ISSUE THREAD

**Issue by shri3k** [gilbarbara/react-joyride#208]
Hi,
This is not an issue in this package but more of a heads-up to people who are using `css-modules` with `modules` turned on in their sass build. There is this [issue](https://github.com/css-modules/css-modules/issues/115) which was raised that has particularly to do with how `keyframes` are named as global and get `localized` on compilation. 

I bring this up because I spent good 3 hours trying to figure out why this pacakge wasn't working as it was supposed to. 

My workaround for this was to copy all the `keyframe` settings from this package's `scss` and overwrite with : 

```scss
@keyframes :global(joyride-tooltip) {
  0% {
    transform: scale(0.1);
  }

  100% {
    opacity: 1;
    transform: perspective(1px) scale(1);
  }
}

@keyframes :global(joyride-beacon-inner) {
  20% {
    opacity: 0.9;
  }

  90% {
    opacity: 0.7;
  }
}

@keyframes :global(joyride-beacon-outer){
  0% {
    transform: scale(1);
  }

  45% {
    opacity: 0.7;
    transform: scale(0.75);
  }

  100% {
    opacity: 0.9;
    transform: scale(1);
  }
}
```

as mentioned by @eriklharper in the previous mentioned [issue](https://github.com/css-modules/css-modules/issues/115#issuecomment-228224639).

Also, thanks for this project. 😄
