### ISSUE TITLE
Add class/style to hole for step styling

### ISSUE THREAD

**Issue by stinoga** [gilbarbara/react-joyride#84]
Would be nice to see an enhancement to allow styling each hole individually, either through a style object like the tooltip styling, or by adding a unique class to each step.

**Comment by stinoga** [comment]
@gilbarbara Any thoughts on how to implement this? I was thinking either add a class based off of the selector name, or off of the current step index. Also, I'd be happy to put together a merge if that helps.

**Comment by gilbarbara** [comment]
The hole has some css fallbacks for safari..

```scss
.joyride-hole {
    border-radius: $joyride-hole-border-radius;
    box-shadow: 0 0 0 9999px $joyride-overlay-color, $joyride-hole-shadow;
    position: absolute;

    &.safari {
      box-shadow: 0 0 999px 9999px $joyride-overlay-color, $joyride-hole-shadow;
    }
}
```

But I'm enabling styling the hole in the `step` styles in version 1.4
